### PR TITLE
Profile uploading, profile attributes, GroupV2: Quality of Life methods

### PR DESCRIPTION
**Pull request by rubdos**
WIP for the ongoing V2 integration and migration in Whisperfish

- [x] Common code for migrating groups V1 to V2
  - [x] Compute master key from V1 ID
- [x] Code for uploading a profile
- [x] Code for uploading profile attributes

### CODE REVIEW

**Comment by rubdos** [comment]
@gferon you may want to look at https://github.com/Michael-F-Bryan/libsignal-service-rs/commit/e2a6dd284732f997304d30a91f261e98aeda581f. This is the equivalent of

```diff+java
commit e8ef62116fafcff757a60867e21e17ac393e7262
Author: Alan Evans <alan@signal.org>
Date:   Mon Sep 28 14:15:19 2020 -0300

    Write gv2-3 capability.

diff --git a/libsignal/service/src/main/java/org/whispersystems/signalservice/api/account/AccountAttributes.java b/libsignal/service/src/main/java/org/whispersystems/signalservice/api/account/AccountAttributes.java
index 2825b0f01..1cee9efb9 100644
--- a/libsignal/service/src/main/java/org/whispersystems/signalservice/api/account/AccountAttributes.java
+++ b/libsignal/service/src/main/java/org/whispersystems/signalservice/api/account/AccountAttributes.java
@@ -119,7 +119,7 @@ public class AccountAttributes {
     @JsonProperty
     private boolean uuid;

-    @JsonProperty("gv2-2")
+    @JsonProperty("gv2-3")
     private boolean gv2;

     @JsonProperty
diff --git a/libsignal/service/src/test/java/org/whispersystems/signalservice/api/account/AccountAttributesTest.java b/libsignal/service/src/test/java/org/whispersystems/signalservice/api/account/AccountAttributesTest.java
index f2cc73126..35f044aba 100644
--- a/libsignal/service/src/test/java/org/whispersystems/signalservice/api/account/AccountAttributesTest.java
+++ b/libsignal/service/src/test/java/org/whispersystems/signalservice/api/account/AccountAttributesTest.java
@@ -28,19 +28,19 @@ public final class AccountAttributesTest {
                  "\"unidentifiedAccessKey\":\"AAAAAAAAAAAAAA==\"," +
                  "\"unrestrictedUnidentifiedAccess\":false," +
                  "\"discoverableByPhoneNumber\":false," +
-                 "\"capabilities\":{\"uuid\":true,\"storage\":true,\"gv2-2\":true}}", json);
+                 "\"capabilities\":{\"uuid\":true,\"storage\":true,\"gv2-3\":true}}", json);
   }

   @Test
   public void gv2_true() {
     String json = JsonUtil.toJson(new AccountAttributes.Capabilities(false, true, false));
-    assertEquals("{\"uuid\":false,\"storage\":false,\"gv2-2\":true}", json);
+    assertEquals("{\"uuid\":false,\"storage\":false,\"gv2-3\":true}", json);
   }

   @Test
   public void gv2_false() {
     String json = JsonUtil.toJson(new AccountAttributes.Capabilities(false, false, false));
-    assertEquals("{\"uuid\":false,\"storage\":false,\"gv2-2\":false}", json);
+    assertEquals("{\"uuid\":false,\"storage\":false,\"gv2-3\":false}", json);
   }

 }
```

.. at the Android side.

**Review by gferon — APPROVED** [review]
Looks good to me! Awesome 🖼️

**Comment by rubdos** [comment]
Good, will try to get this cleaned and merged by tonight.

**Comment by rubdos** [comment]
Clippy should be happy at this point. Build failure is because of beta versions with Actix; should be fixed separately. Merging this in, hold your horses!

**Pull request merged**
